package org.onebusaway.federations.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

import org.onebusaway.federations.FederatedService;

/**
 * Directs the creation of a {@link FederatedServiceMethodInvocationHandler},
 * where a method returns either a {@link List} or a {@link Map} and the
 * federated method return value is generated by calling each
 * {@link FederatedService} in turn an aggregating the results with the
 * appropriate collection.
 * 
 * <pre class="code">
 * @FederatedByAggregateMethod
 * public List<String> getValuesAsList();
  
 * @FederatedByAggregateMethod
 * public Map<String,String> getValuesAsMap();
 * </pre>
 * 
 * @author bdferris
 * @see FederatedServiceMethodInvocationHandlerFactory
 * @see FederatedByAggregateMethodInvocationHandlerImpl
 */
@Retention(value = RetentionPolicy.RUNTIME)
@Target(value = ElementType.METHOD)
public @interface FederatedByAggregateMethod {

}
